//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.RecurringJobAdmin.Dashboard.Content.resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecurringJobAdminStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecurringJobAdminStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangfire.RecurringJobAdmin.Dashboard.Content.resx.RecurringJobAdminStrings", typeof(RecurringJobAdminStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        internal static string Common_Arguments {
            get {
                return ResourceManager.GetString("Common_Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments Types.
        /// </summary>
        internal static string Common_ArgumentsTypes {
            get {
                return ResourceManager.GetString("Common_ArgumentsTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string Common_Class {
            get {
                return ResourceManager.GetString("Common_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to DELETE job {0}?.
        /// </summary>
        internal static string Common_DeleteThisJobConfirm {
            get {
                return ResourceManager.GetString("Common_DeleteThisJobConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Common_Enabled {
            get {
                return ResourceManager.GetString("Common_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Common_Input {
            get {
                return ResourceManager.GetString("Common_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job ID.
        /// </summary>
        internal static string Common_JobId {
            get {
                return ResourceManager.GetString("Common_JobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Common_Method {
            get {
                return ResourceManager.GetString("Common_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide complete path to the class! Example: My.Namespace.MyClass.
        /// </summary>
        internal static string JobExtension_ClassInputHint {
            get {
                return ResourceManager.GetString("JobExtension_ClassInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication error.
        /// </summary>
        internal static string JobExtension_CommunicationError {
            get {
                return ResourceManager.GetString("JobExtension_CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        internal static string JobExtension_Cron_Choice {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string JobExtension_Cron_Days {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        internal static string JobExtension_Cron_Every {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string JobExtension_Cron_Friday {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string JobExtension_Cron_Hours {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up To.
        /// </summary>
        internal static string JobExtension_Cron_Max {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string JobExtension_Cron_Min {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string JobExtension_Cron_Minutes {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string JobExtension_Cron_Monday {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string JobExtension_Cron_Months {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string JobExtension_Cron_Range {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string JobExtension_Cron_Saturday {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string JobExtension_Cron_Step {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string JobExtension_Cron_Sunday {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string JobExtension_Cron_Thursday {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string JobExtension_Cron_Tuesday {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        internal static string JobExtension_Cron_UI {
            get {
                return ResourceManager.GetString("JobExtension_Cron_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string JobExtension_Cron_Wednesday {
            get {
                return ResourceManager.GetString("JobExtension_Cron_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days of the Week.
        /// </summary>
        internal static string JobExtension_Cron_WeekDays {
            get {
                return ResourceManager.GetString("JobExtension_Cron_WeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (s?) - seconds, optional; (m) - minutes, mandatory; (h) - hours, mandatory; (d) - day of the month, mandatory; (M) - month of the year, mandatory; (wd) - day of the week, mandatory
        ///&lt;br /&gt;Possible values: * = value is not considered; number = execute exactly at the specified number; number-number = range in which to execute; */2 = execute every 2 units starting from 0; number/3 = execute every 3 units starting at the number, up to the last unit; number-number/3 = execute every 3 units in the range, starting [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobExtension_CronInputDetailedExplaination {
            get {
                return ResourceManager.GetString("JobExtension_CronInputDetailedExplaination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: (s?) (m) (h) (d) (M) (wd). Explaination: .
        /// </summary>
        internal static string JobExtension_CronInputHint {
            get {
                return ResourceManager.GetString("JobExtension_CronInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Editor.
        /// </summary>
        internal static string JobExtension_JobEditor {
            get {
                return ResourceManager.GetString("JobExtension_JobEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the following error(s):.
        /// </summary>
        internal static string JobExtension_JobEditorErrorListHeader {
            get {
                return ResourceManager.GetString("JobExtension_JobEditorErrorListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string JobExtension_Timeout {
            get {
                return ResourceManager.GetString("JobExtension_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Configuration.
        /// </summary>
        internal static string JobExtension_Title {
            get {
                return ResourceManager.GetString("JobExtension_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stopped jobs found..
        /// </summary>
        internal static string StoppedJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("StoppedJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped Jobs.
        /// </summary>
        internal static string StoppedJobsPage_Title {
            get {
                return ResourceManager.GetString("StoppedJobsPage_Title", resourceCulture);
            }
        }
    }
}
